// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test/go-micro/proto/greeter/greeter.proto

/*
Package greeter is a generated protocol buffer package.

It is generated from these files:
	test/go-micro/proto/greeter/greeter.proto

It has these top-level messages:
	Request
	Response
*/
package greeter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Response struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Response)(nil), "Response")
}

func init() { proto.RegisterFile("test/go-micro/proto/greeter/greeter.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x2c, 0x49, 0x2d, 0x2e,
	0xd1, 0x4f, 0xcf, 0xd7, 0xcd, 0xcd, 0x4c, 0x2e, 0xca, 0xd7, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7,
	0x4f, 0x2f, 0x4a, 0x4d, 0x2d, 0x49, 0x2d, 0x82, 0xd1, 0x7a, 0x60, 0x51, 0x25, 0x59, 0x2e, 0xf6,
	0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x21, 0x2e, 0x96, 0xbc, 0xc4, 0xdc, 0x54, 0x09,
	0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x5b, 0x49, 0x86, 0x8b, 0x23, 0x28, 0xb5, 0xb8, 0x20,
	0x3f, 0xaf, 0x38, 0x55, 0x48, 0x80, 0x8b, 0x39, 0xb7, 0x38, 0x1d, 0x2a, 0x0d, 0x62, 0x1a, 0x69,
	0x72, 0xb1, 0xbb, 0x43, 0x4c, 0x13, 0x92, 0xe3, 0x62, 0xf5, 0x48, 0xcd, 0xc9, 0xc9, 0x17, 0xe2,
	0xd0, 0x83, 0x9a, 0x27, 0xc5, 0xa9, 0x07, 0xd3, 0xaa, 0xc4, 0x90, 0xc4, 0x06, 0xb6, 0xce, 0x18,
	0x10, 0x00, 0x00, 0xff, 0xff, 0x51, 0x8f, 0x33, 0x13, 0x9b, 0x00, 0x00, 0x00,
}
