package main

import (
	"fmt"
	"encoding/json"
)

type AutoGenerated struct {
	AttrOne string `yaml:"attrOne"`
	AttrTwo *InnerStruct `yaml:"attrTwo"`
}

type InnerStruct struct {
	AttrThree string `yaml:"attrThree"`
	AttrFour  string `yaml:"attrFour"`
}

func main() {
	str := `
{
	"attrOne": "abc",
	"attrTwo": {
		"attrThree": "def",
		"attrFour": "ghi"
	}
}
`
	a := new(AutoGenerated)
	json.Unmarshal([]byte(str), a)
	fmt.Printf("%v\n", a)
}
